#!/bin/bash
# shellcheck disable=SC2086,SC2001,SC2154,SC1091
set -e

# grub-mkconfig helper script.
# Copyright (C) 2006,2007,2008,2009  Free Software Foundation, Inc.
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

. "$pkgdatadir/grub-mkconfig_lib"
. /etc/default/grub

export TEXTDOMAIN=grub
export TEXTDOMAINDIR="${datarootdir}/locale"

CLASS="--class bassos --class android --class os"
OS="Android"
TITLE="BassOS a14 $(grep 'ro.bliss.version=' /system/build.prop | awk -F'=' '{print $2}')"

ADVANCED_ARGS=(
	"Debug mode: DEBUG=2 androidboot.enable_console=1"
	"No Modeset: nomodeset"
	"No hwaccel: HWACCEL=0"
)

RECOVERY_ARGS=(
	""
	"Debug mode: DEBUG=2 androidboot.enable_console=1"
	"RGBX_8888 color mode: androidboot.pixel_format=RGBX_8888"
	"ABGR_8888 color mode: androidboot.pixel_format=ABGR_8888"
	"ARGB_8888 color mode: androidboot.pixel_format=ARGB_8888"
	"BGRA_8888 color mode: androidboot.pixel_format=BGRA_8888"
	"RGBA_8888 color mode: androidboot.pixel_format=RGBA_8888"
	"BGRX_8888 color mode: androidboot.pixel_format=BGRX_8888"
)

DESKTOP_ARGS=(
	"multi-display DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 PC_MODE=1 BASS_DESKTOPUI=1"
	"multi-display navigation & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 PC_MODE=1 BASS_DESKTOPUI=1"
	"multi-display mouse, navigation & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_MOUSE_PRESENTATION=1 PC_MODE=1 BASS_DESKTOPUI=1"
	"multi-display IME & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 PC_MODE=1 BASS_DESKTOPUI=1"
	"multi-display navigation, IME & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 PC_MODE=1 BASS_DESKTOPUI=1"
	"multi-display mouse, navigation, IME & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FORCE_MOUSE_PRESENTATION=1 PC_MODE=1 BASS_DESKTOPUI=1"
)

HYBRID_DESKTOP_ARGS=(
	"multi-display DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 BASS_DESKTOPUI=1"
	"multi-display navigation & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 BASS_DESKTOPUI=1"
	"multi-display mouse, navigation & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_MOUSE_PRESENTATION=1 BASS_DESKTOPUI=1"
	"multi-display IME & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 BASS_DESKTOPUI=1"
	"multi-display navigation, IME & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 BASS_DESKTOPUI=1"
	"multi-display mouse, navigation, IME & DesktopUI: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 HYBRID_PC_MODE=1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FORCE_MOUSE_PRESENTATION=1 BASS_DESKTOPUI=1"
)

RESTRICTED_LOCKDOWN_ARGS=(
	"Single display: splash=silent,fadein,fadeout logo FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=0 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=0 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=lockdown loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Primary Touch: splash=silent,fadein,fadeout logo FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=0 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=0 androidboot.force.disable_external_display_focus=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=lockdown loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch: splash=silent,fadein,fadeout logo FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=lockdown loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch (no navbar): splash=silent,fadein,fadeout logo FORCE_DISABLE_NAVIGATION=true FORCE_DISABLE_NAV_HANDLE=true FORCE_DISABLE_NAV_TASKBAR=true FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=lockdown loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual & mouse: splash=silent,fadein,fadeout logo FORCE_MOUSE_PRESENTATION=1 FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=lockdown loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch & mouse (no navbar): splash=silent,fadein,fadeout logo FORCE_MOUSE_PRESENTATION=1 FORCE_DISABLE_NAVIGATION=true FORCE_DISABLE_NAV_HANDLE=true FORCE_DISABLE_NAV_TASKBAR=true FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=lockdown loglevel=0 console=tty6 BASS_KIOSKUI=1"
)

RESTRICTED_ADMIN_ARGS=(
	"single display: logo FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=0 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=0 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Primary Touch: logo FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=0 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=0 androidboot.force.disable_external_display_focus=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch: logo FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch (no navbar): logo FORCE_DISABLE_NAVIGATION=true FORCE_DISABLE_NAV_HANDLE=true FORCE_DISABLE_NAV_TASKBAR=true FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch & mouse: logo FORCE_MOUSE_PRESENTATION=1 FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Multi display Dual Touch & mouse (no navbar): logo FORCE_MOUSE_PRESENTATION=1 FORCE_DISABLE_NAVIGATION=true FORCE_DISABLE_NAV_HANDLE=true FORCE_DISABLE_NAV_TASKBAR=true FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin loglevel=0 console=tty6 BASS_KIOSKUI=1"
	"Debugging Admin: logo FFMPEG_OMX_CODEC=1 FFMPEG_CODEC2_PREFER=1 androidboot.bliss.bootmode=admin androidboot.enable_console=1 DEBUG=2"
)

TABLET_ARGS=(
	"TabletUI Single display: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DESKTOP_ON_EXTERNAL=0 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 BASS_TABLETUI=1"
	"TabletUI Multi display (PDFE): splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=0 androidboot.per_display_focus_enabled=true BASS_TABLETUI=1"
	"TabletUI Multi display: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 BASS_TABLETUI=1"
	"TabletUI Multi display (PDFE): splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 androidboot.per_display_focus_enabled=true BASS_TABLETUI=1"
	"multi-display navigation: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 BASS_TABLETUI=1"
	"multi-display mouse, navigation: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_MOUSE_PRESENTATION=1 BASS_TABLETUI=1"
	"multi-display IME: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 BASS_TABLETUI=1"
	"multi-display navigation, IME: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 BASS_TABLETUI=1"
	"multi-display mouse, navigation, IME: splash=silent,fadein,fadeout logo androidboot.force.win_as_home=1 androidboot.bliss.window.animation.scale=0.1 FORCE_DISABLE_NAV_HANDLE=1 loglevel=0 console=tty6 FORCE_DESKTOP_ON_EXTERNAL=1 FORCE_NAVBAR_ON_SECONDARY_DISPLAYS=1 FORCE_IME_ON_SECONDARY_DISPLAYS=1 FORCE_MOUSE_PRESENTATION=1 BASS_TABLETUI=1"
)

disk="$(prepare_grub_to_access_device "$GRUB_DEVICE")"

# Extra indentation to add to menu entries in a submenu. We're not in a submenu
# yet, so it's empty. In a submenu it will be equal to '\t' (one tab).
ROOT_DEVICE=$GRUB_DEVICE
ROOT_UUID=$(${grub_probe} --device "$ROOT_DEVICE" --target=fs_uuid 2>/dev/null)

[ "$ROOT_UUID" ] && ROOT_DEVICE="UUID=$ROOT_UUID"

android_entry() {
	local extra_title extra_args

	# shellcheck disable=SC2015
	extra_title=$1 &&
		shift &&
		extra_args=$* ||
		:

	echo "menuentry '$(echo "$TITLE${extra_title:+ - $extra_title}" | grub_quote)' ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-\$SLOT${extra_args:+-${extra_args// /_}}' {"

	save_default_entry | grub_add_tab

	# Use ELILO's generic "efifb" when it's known to be available.
	# FIXME: We need an interface to select vesafb in case efifb can't be used.
	if [ ! "$GRUB_GFXPAYLOAD_LINUX" ]; then
		echo "	load_video"
		grep -qx "CONFIG_FB_EFI=y" "${config}" 2>/dev/null &&
			grep -qx "CONFIG_VT_HW_CONSOLE_BINDING=y" "${config}" 2>/dev/null &&
			echo "	set gfxpayload=auto"

	else
		[ "$GRUB_GFXPAYLOAD_LINUX" = text ] ||
			echo "	load_video"
		echo "	set gfxpayload=$GRUB_GFXPAYLOAD_LINUX"
	fi

	echo "	insmod gzio"
	echo "$disk" | sed "s/^/$grub_tab/gm"
	echo "	linux $SRC/kernel\$SLOT \$CMDLINE androidboot.mode=\$MODE $extra_args ROOT=$ROOT_DEVICE root=/dev/ram0 SRC=$SRC androidboot.slot_suffix=\$SLOT"
	echo "	initrd $SRC/initrd\$SLOT.img"
	echo "}
"
}

entry() { android_entry "$@" | sed "s/^/$submenu_indentation	/gm"; }

# android.cfg is where BootCTL HAL updates current slot suffix after OTA
cat <<'EOF'
source $prefix/android.cfg
export SLOT
export CMDLINE
export MODE
EOF

submenu_indentation=""
android_entry

submenu_indentation=$grub_tab


TITLE=$old_title
echo "submenu '$(echo "Bass boot options" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Bassboot' {"
TITLE=""
echo "submenu '$(echo "TabletUI" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Lockdownadmin' {"
for arg in "${TABLET_ARGS[@]}"; do
	entry "${arg%:*}" ${arg#*:}
done
echo "}"

echo "submenu '$(echo "Hybrid-DesktopUI" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-HDesktop' {"
for arg in "${HYBRID_DESKTOP_ARGS[@]}"; do
	entry "${arg%:*}" ${arg#*:}
done
echo "}"

echo "submenu '$(echo "DesktopUI" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Desktop' {"
for arg in "${DESKTOP_ARGS[@]}"; do
	entry "${arg%:*}" ${arg#*:}
done
echo "}"

echo "submenu '$(echo "Kiosk" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Kiosk' {"

echo "submenu '$(echo "Lockdown" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Lockdown' {"
for arg in "${RESTRICTED_LOCKDOWN_ARGS[@]}"; do
	entry "${arg%:*}" ${arg#*:}
done
echo "}"

echo "submenu '$(echo "Admin" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Lockdownadmin' {"
for arg in "${RESTRICTED_ADMIN_ARGS[@]}"; do
	entry "${arg%:*}" ${arg#*:}
done
echo "}"

echo "}"

echo "}"

old_title=$TITLE
echo "submenu '$(echo "Recovery modes for $TITLE" | grub_quote)' --class recovery ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Recovery' {"
TITLE="$TITLE - Recovery Mode"
for arg in "${RECOVERY_ARGS[@]}"; do
	entry "${arg%:*}" androidboot.mode=recovery androidboot.force_normal_boot=0 ${arg#*:}
done
echo "}"

TITLE=$old_title
echo "submenu '$(echo "Advanced options for $TITLE" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '$OS-${TITLE// /_}-Advanced' {"
for arg in "${ADVANCED_ARGS[@]}"; do
	entry "${arg%:*}" ${arg#*:}
done
echo "}"
